### ISSUE TITLE
Possibly need to remove location.href regex check?

### ISSUE THREAD

**Issue by testpushpleaseignore** [giacomoferretti/forks-diff#1]
For the below code in your main.js file, should this be left out of your code? It seems that if you navigate to the Forks page from the Insights tab, the page URL doesn't update to match the regex while navigating to it.

[`if (githubUrlRegex.test(location.href)) {`](https://github.com/giacomoferretti/forks-diff/blob/106d8db8379f79ca36ffaa294be2f97d76140c2c/js/main.js#L136)

**Comment by giacomoferretti** [comment]
It seems to be GitHub's fault, but I'll fix it anyway. Thank you for the report!

**Comment by giacomoferretti** [comment]
Which browser are you using?

Because I can only reproduce the problem with Firefox.

**Comment by testpushpleaseignore** [comment]
Yeah it definitely seems to be GitHub's fault, I'm wondering if it has to do with the `<turbo-frame>` element (id="repo-content-turbo-frame")? I'm assuming that it's working like an iframe, but I've never worked with them myself.

But otherwise I'm on Chrome right now, Version 104.0.5112.81 (Official Build) (64-bit). I tried to see if there was a way to disable this sort of turbo-frame from GitHub (assuming that this is the issue), but no luck on my end.

**Comment by giacomoferretti** [comment]
This was not properly fixed, it was caused by the extension itself, as explained in #2.

**Comment by giacomoferretti** [comment]
Fixed now!
